export const optionName = {
  base: "ร่างกาย",
  eyes: "ตา",
  eyebrows: "คิ้ว",
  mouth: "ปาก",
  hair: "ผม",
  shirt: "เสื้อ",
  pants: "กางเกง",
  outer: "เสื้อคลุม",
  shoes: "รองเท้า",
};

export const optionImages = {
  base: ["base-1", "base-2", "base-3", "base-4", "base-5"],
  hair: {
    "hair-1": ["default"],
    "hair-2": ["default"],
    "hair-3": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-4": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-5": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-6": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-7": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-8": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-9": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-10": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-11": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-12": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-13": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-14": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
    "hair-15": [
      "brown",
      "black",
      "blonde",
      "blue",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "yellow",
    ],
  },
  eyes: {
    "eyes-1": ["black", "blue", "brown", "green", "gray", "pink"],
    "eyes-2": ["black", "blue", "brown", "green", "gray", "pink"],
    "eyes-3": ["black", "blue", "brown", "green", "gray", "pink"],
    "eyes-4": ["default"],
    "eyes-5": ["default"],
    "eyes-6": ["default"],
  },
  eyebrows: ["eyebrows-1", "eyebrows-2", "eyebrows-3"],
  mouth: [
    "mouth-1",
    "mouth-2",
    "mouth-3",
    "mouth-4",
    "mouth-5",
    "mouth-6",
    "mouth-7",
    "mouth-8",
    "mouth-9",
  ],
  shirt: {
    "shirt-1": ["gray", "black", "red", "white"],
    "shirt-2": ["black", "gray", "red", "white"],
    "shirt-3": ["red", "gray", "black", "white"],
    "shirt-4": ["white", "gray", "red", "black"],
    "shirt-5": ["gray", "black", "red", "white"],
    "shirt-6": ["white", "gray", "red", "black"],
    "shirt-7": ["black", "gray", "red", "white"],
    "shirt-8": ["gray", "black", "red", "white"],
    "shirt-9": ["red", "gray", "black", "white"],
    "shirt-10": ["black", "gray", "red", "white"],
  },
  pants: {
    "pants-1": ["gray", "blue", "white", "black"],
    "pants-2": ["elephant", "gray", "white", "black"],
    "pants-3": ["gray", "blue", "white", "black"],
    "pants-4": ["gray", "blue", "white", "black"],
    "pants-5": ["gray", "blue", "white", "black"],
    "pants-6": ["navy", "gray", "blue", "white", "black"],
    "pants-7": ["navy", "gray", "blue", "white", "black"],
    "pants-8": ["navy", "gray", "blue", "white", "black"],
  },
  outer: {
    "outer-1": ["default"],
    "outer-2": ["black", "blue", "gray", "pink", "red", "white"],
    "outer-3": ["pink", "blue", "brown", "cream", "gray", "black", "white"],
    "outer-4": ["gray", "blue", "brown", "cream", "black", "pink", "white"],
    "outer-5": ["white", "blue", "brown", "cream", "gray", "pink", "black"],
    "outer-6": ["cream", "blue", "brown", "black", "gray", "pink", "white"],
  },
  shoes: {
    "shoes-1": ["default"],
    "shoes-2": ["black", "gray", "red", "brown", "white"],
    "shoes-3": ["brown", "gray", "black", "red", "white"],
    "shoes-4": ["black", "gray", "red", "brown", "white"],
    "shoes-5": ["gray", "red", "black", "brown", "white"],
    "shoes-6": ["black", "brown", "white"],
    "shoes-7": ["brown", "white", "black"],
    "shoes-8": ["black", "gray", "red", "brown", "white"],
    "shoes-9": ["gray", "red", "black", "brown", "white"],
  },
};

export const initialOption = {
  base: optionImages.base[0],
  hair: `hair-1-${optionImages.hair["hair-1"][0]}`,
  eyes: `eyes-1-${optionImages.eyes["eyes-1"][0]}`,
  eyebrows: optionImages.eyebrows[0],
  mouth: `mouth-1`,
  shirt: `shirt-1-${optionImages.shirt["shirt-1"][1]}`,
  pants: `pants-5-${optionImages.pants["pants-5"][0]}`,
  outer: `outer-1-${optionImages.outer["outer-1"][0]}`,
  shoes: `shoes-1-${optionImages.shoes["shoes-1"][0]}`,
  tucked: false,
};

export const zoomedOptions = ["eyes", "eyebrows", "mouth", "outer", "shirt"];

export const canBeEmpty = [
  "outer",
  "shirt",
  "pants",
  "shoes",
  "hair",
  "eyebrows",
];
